# Generated by Django 5.2.3 on 2025-06-25 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_tracker', '0003_userprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='financial_risk',
            field=models.CharField(choices=[('NO', 'No Risk'), ('MOD', 'Moderate Risk'), ('HIGH', 'High Risk')], default='MOD', max_length=4),
        ),
    ]
