# Generated by Django 5.2.3 on 2025-06-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_tracker', '0004_userprofile_financial_risk'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_emoji',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
